/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zxzx74147_mediacore_components_audio_mixer_AudioNdkInterface */

#ifndef _Included_com_zxzx74147_mediacore_components_audio_mixer_AudioNdkInterface
#define _Included_com_zxzx74147_mediacore_components_audio_mixer_AudioNdkInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zxzx74147_mediacore_components_audio_mixer_AudioNdkInterface
 * Method:    pcm_convert
 * Signature: ([BIII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_zxzx74147_mediacore_components_audio_mixer_AudioNdkInterface_pcm_1convert
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_zxzx74147_mediacore_components_audio_mixer_AudioNdkInterface
 * Method:    mix
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_zxzx74147_mediacore_components_audio_mixer_AudioNdkInterface_mix
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
